CREATE TABLE teamK_words (
                             id          SERIAL PRIMARY KEY,
                             word        VARCHAR(50)  NOT NULL,
                             hint        VARCHAR(255) NOT NULL,
                             category    VARCHAR(20)  NOT NULL,
                             word_length INT          NOT NULL
);

INSERT INTO teamK_words (word, hint, category, word_length) VALUES

-- OOP / UML
('OBJECT',          'En instans af en klasse med egne attributter og metoder',                            'OOP', 6),
('CLASS',           'Skabelonen der bruges til at oprette objekter',                                      'OOP', 5),
('CONSTRUCTOR',     'Metoden der kører automatisk når et nyt objekt oprettes',                            'OOP', 11),
('GETTER',          'En metode der returnerer værdien af en privat attribut',                             'OOP', 6),
('SETTER',          'En metode der ændrer værdien af en privat attribut',                                 'OOP', 6),
('TOSTRING',        'En metode der returnerer en tekst-repræsentation af et objekt',                      'OOP', 8),
('PRIVATE',         'Access modifier der gør en attribut kun tilgængelig inde i klassen',                 'OOP', 7),
('PUBLIC',          'Access modifier der gør noget tilgængeligt overalt i programmet',                    'OOP', 6),
('PROTECTED',       'Access modifier der tillader adgang i klassen og dens subklasser',                   'OOP', 9),
('INHERITANCE',     'Når en klasse overtager egenskaber og metoder fra en anden klasse',                  'OOP', 11),
('SUPERCLASS',      'Moderklassen som andre klasser arver fra',                                           'OOP', 10),
('SUBCLASS',        'Klassen der arver fra en anden og kan udvide dens funktionalitet',                   'OOP', 8),
('EXTENDS',         'Nøgleordet der bruges i Java til at lave nedarvning',                                'OOP', 7),
('SUPER',           'Nøgleord til at kalde constructoren eller metoder i moderklassen',                   'OOP', 5),
('INTERFACE',       'En kontrakt der definerer hvilke metoder en klasse skal have',                       'OOP', 9),
('IMPLEMENTS',      'Nøgleordet der bruges når en klasse opfylder et interface',                          'OOP', 10),
('POLYMORPHISM',    'Når samme metode opfører sig forskelligt afhængigt af objektets type',               'OOP', 12),
('ABSTRACT',        'En klasse eller metode der ikke kan bruges direkte men skal arves',                  'OOP', 8),
('OVERRIDE',        'Når en subklasse skriver sin egen version af en nedarvet metode',                    'OOP', 8),
('UML',             'Standardsprog til at tegne diagrammer over softwaredesign',                          'OOP', 3),
('CLASSDIAGRAM',    'Diagram der viser klasser, attributter, metoder og relationer',                      'OOP', 12),
('DOMAINMODEL',     'Oversigt over de vigtigste begreber og sammenhænge i et system',                     'OOP', 11),
('ASSOCIATION',     'En relation mellem to klasser — de kender til hinanden',                             'OOP', 11),
('AGGREGATION',     'Relation hvor en klasse indeholder en anden men kan eksistere uden den',             'OOP', 11),
('COMPOSITION',     'Stærk relation hvor den ene klasse ikke kan eksistere uden den anden',               'OOP', 11),

-- Java
('VARIABLE',        'En navngivet beholder der gemmer en værdi i hukommelsen',                            'Java', 8),
('DATATYPE',        'Definerer hvilken slags data en variabel kan indeholde',                             'Java', 8),
('INT',             'Den simpleste heltalsdatatype i Java',                                               'Java', 3),
('DOUBLE',          'Datatype til kommatal som f.eks. 3.14',                                              'Java', 6),
('BOOLEAN',         'Kan kun være true eller false — opkaldt efter George Boole',                         'Java', 7),
('STRING',          'En tekst-datatype — egentlig en klasse i Java',                                      'Java', 6),
('ARRAY',           'En liste med fast størrelse der indeholder elementer af samme type',                 'Java', 5),
('ARRAYLIST',       'En dynamisk liste der kan vokse og skrumpe i størrelse',                             'Java', 9),
('LOOP',            'Gentager en blok kode så længe en betingelse er sand',                               'Java', 4),
('FOR',             'Løkke der kører et bestemt antal gange med en tæller',                               'Java', 3),
('WHILE',           'Løkke der kører så længe en betingelse er opfyldt',                                  'Java', 5),
('FOREACH',         'Løkke der automatisk gennemløber hvert element i en samling',                        'Java', 7),
('METHOD',          'En navngivet blok kode der udfører en specifik opgave',                              'Java', 6),
('RETURNTYPE',      'Definerer hvilken type data en metode sender tilbage',                               'Java', 10),
('PARAMETER',       'En variabel der modtager en værdi når en metode kaldes',                             'Java', 9),
('VOID',            'Returtype der betyder at metoden ikke returnerer noget',                             'Java', 4),
('SCANNER',         'Java-klasse til at læse input fra tastatur eller fil',                               'Java', 7),
('TRYCATCH',        'Fejlhåndtering der fanger exceptions og forhindrer programmet i at crashe',          'Java', 8),
('EXCEPTION',       'En fejl der opstår under kørsel og kan kastes og fanges',                            'Java', 9),
('THROWS',          'Nøgleord der angiver at en metode kan kaste en bestemt fejl',                        'Java', 6),
('LENGTH',          'String-metode der returnerer hvor mange tegn en tekst har',                          'Java', 6),
('CHARAT',          'String-metode der returnerer et enkelt tegn på en bestemt position',                 'Java', 6),
('INDEXOF',         'ArrayList- eller String-metode der finder positionen af et element',                 'Java', 7),
('CONTAINS',        'Metode der returnerer true hvis en liste eller streng indeholder en bestemt værdi',  'Java', 8),
('INSTANCEOF',      'Operator der tjekker om et objekt er af en bestemt type',                            'Java', 10),
('SWITCH',          'Alternativ til mange if-else sætninger — matcher på en specifik værdi',              'Java', 6),
('IFELSE',          'Betinget udførelse — kode der kun kører når noget er sandt',                         'Java', 6),

-- Database
('DATABASE',          'En organiseret samling af data der kan søges og opdateres',                        'Database', 8),
('TABLE',             'Den grundlæggende struktur i en relationsdatabase med rækker og kolonner',         'Database', 5),
('QUERY',             'En forespørgsel til databasen skrevet i SQL',                                      'Database', 5),
('SELECT',            'SQL-kommando til at hente data fra en tabel',                                      'Database', 6),
('INSERT',            'SQL-kommando til at tilføje en ny række til en tabel',                             'Database', 6),
('UPDATE',            'SQL-kommando til at ændre eksisterende data i en tabel',                           'Database', 6),
('DELETE',            'SQL-kommando til at fjerne rækker fra en tabel',                                   'Database', 6),
('WHERE',             'SQL-klausul der filtrerer hvilke rækker der returneres',                           'Database', 5),
('JOIN',              'Kombinerer rækker fra to tabeller baseret på en fælles kolonne',                   'Database', 4),
('PRIMARYKEY',        'Unik identifikator for hver række i en tabel — forkortet PK',                      'Database', 10),
('FOREIGNKEY',        'Felt der peger på primærnøglen i en anden tabel',                                  'Database', 10),
('INDEX',             'Gør søgning i en database hurtigere',                                              'Database', 5),
('NORMALISATION',     'Processen med at strukturere en database for at undgå gentagelser',                'Database', 13),
('RELATION',          'Forbindelsen mellem to tabeller via nøgler',                                       'Database', 8),
('JDBC',              'Java-bibliotek til at forbinde din kode med en database',                          'Database', 4),
('RESULTSET',         'Det objekt du får tilbage fra en SQL-forespørgsel i Java',                         'Database', 9),
('AGGREGATE',         'SQL-funktioner som COUNT, SUM, AVG der beregner på tværs af rækker',               'Database', 9),
('GROUPBY',           'SQL-klausul der samler rækker med samme værdi i grupper',                          'Database', 7),

-- Web / Frontend
('HTML',         'Sproget der definerer strukturen og indholdet af en webside',                           'Web', 4),
('CSS',          'Sproget der styrer udseende og layout på en webside',                                   'Web', 3),
('JAVASCRIPT',   'Programmeringssproget der gør websider interaktive',                                    'Web', 10),
('DOM',          'Træstruktur der repræsenterer alle elementer på en webside',                             'Web', 3),
('SELECTOR',     'CSS-udtryk der vælger hvilke HTML-elementer der skal styles',                           'Web', 8),
('FLEXBOX',      'CSS-layout-system til at placere elementer i en række eller kolonne',                   'Web', 7),
('GRID',         'CSS-layout-system til at placere elementer i rækker og kolonner',                       'Web', 4),
('RESPONSIVE',   'Design der automatisk tilpasser sig skærmens størrelse',                                'Web', 10),
('JSON',         'Tekstformat til at udveksle data — bruges meget i web-APIer',                           'Web', 4),
('API',          'En grænseflade der lader din kode kommunikere med en ekstern service',                  'Web', 3),
('ENDPOINT',     'En specifik URL på en server der håndterer en bestemt type forespørgsel',               'Web', 8),
('HTTP',         'Protokollen bag al kommunikation på internettet',                                       'Web', 4),
('GET',          'HTTP-metode til at hente data fra en server',                                           'Web', 3),
('POST',         'HTTP-metode til at sende data til en server',                                           'Web', 4),
('STATUSCODE',   'Tal der fortæller om en HTTP-forespørgsel lykkedes — f.eks. 200 eller 404',             'Web', 10),
('LOCALHOST',    'Din egen computer som server — standardadresse til lokal udvikling',                    'Web', 9),
('BACKEND',      'Serverside-kode der håndterer logik og data bag kulisserne',                            'Web', 7),
('FRONTEND',     'Alt hvad brugeren ser og interagerer med i browseren',                                  'Web', 8),

-- Git
('GIT',        'Versionsstyringssystem der sporer ændringer i din kode over tid',                         'Git', 3),
('COMMIT',     'Et snapshot af dine ændringer gemt med en beskrivende besked',                            'Git', 6),
('BRANCH',     'En parallel version af koden til at arbejde på en feature isoleret',                     'Git', 6),
('MERGE',      'Kombinerer to branches til én',                                                           'Git', 5),
('PUSH',       'Sender dine lokale commits op til et remote repository',                                  'Git', 4),
('PULL',       'Henter de nyeste ændringer fra et remote repository ned til dig',                         'Git', 4),
('CLONE',      'Kopierer et helt repository fra GitHub til din computer',                                 'Git', 5),
('REPOSITORY', 'Mappen der gemmer hele din kode og historik i Git',                                       'Git', 10),
('CONFLICT',   'Opstår når to personer har ændret samme linje kode i Git',                                'Git', 8),
('GITIGNORE',  'Fil der fortæller Git hvilke filer der ikke skal spores',                                 'Git', 9);